include: all_rules.yaml

analyzer:
  plugins:
    - dart_code_metrics
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    included_file_warning: ignore
    invalid_use_of_visible_for_testing_member: error
  exclude: ["**/*.g.dart"]

linter:
  rules:
    always_specify_types: false
    avoid_classes_with_only_static_members: false
    avoid_final_parameters: false # opposite of `prefer_final_parameters`.
    prefer_double_quotes: false # opposite of `prefer_single_quotes`.
    prefer_relative_imports: false # opposite of `prefer_relative_imports`.
    public_member_api_docs: false
    unnecessary_final: false # contradiction with `prefer_final_parameters` and `prefer_final_locals`.

dart_code_metrics:
  extends:
    - package:dart_code_metrics/presets/all.yaml
  rules:
    - avoid-passing-async-when-sync-expected: false
    - arguments-ordering:
        child-last: true
    - member-ordering:
        alphabetize: true
        order:
          - constructors 
          - private-fields
          - public-fields
    - no-object-declaration: false
    - prefer-single-widget-per-file:
        ignore-private-widgets: true