name: appcenter_sdk_flutter
description: Development repository for the App Center SDK for Flutter
version: 0.0.1
repository: https://github.com/lsaudon/appcenter_sdk_flutter

environment:
  sdk: ">=2.18.5 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.8.0
  plugin_platform_interface: ^2.1.3

dev_dependencies:
  dart_code_metrics: ^5.2.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  pigeon: ^4.2.10

dependency_overrides:
  analyzer: ^5.2.0

flutter:
  plugin:
    platforms:
      android:
        package: fr.lsaudon.appcenter_sdk_flutter
        pluginClass: AppCenterSdkFlutterPlugin
      ios:
        pluginClass: AppCenterSdkFlutterPlugin
